version: '3'
services:

  client:
    build:
      context: .
      dockerfile: Dockerfile
    image: greeter_client
    network_mode: host
    environment:
      ADDRESS: "${ADDRESS:-localhost:8000}"
