resources:
- '@type': type.googleapis.com/envoy.api.v2.ClusterLoadAssignment
  cluster_name: helloworld
  endpoints:
  - lb_endpoints:
    - endpoint:
        address:
          socket_address: {address: 172.22.0.3, port_value: 80}
version_info: '1'
